name: ChatOps-SWAP

env:
  RESOURCE_GROUP: cd-demoactions
  LOCATION: westus2
  PLAN_NAME: cd-demoactionsplan
  SKU: S1
  WEB_APP_NAME: cd-demoactions
  SLOT_NAME: blue
  DOTNET_VERSION: 3.1.100

on:
  issue_comment:
    types: [ created, edited ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/swap:')
    
    steps:
    #- uses: actions/checkout@v2

    - name: "Set env variables from chat message"
      run: |
        pattern="^\/swap\:(\.+)\,(\.+)$"
        [[ "${{ github.event.comment.body }}" =~ $pattern ]]
        echo ::set-env name=SLOT_1_NAME::"${BASH_REMATCH[1]}"
        echo ::set-env name=SLOT_2_NAME::"${BASH_REMATCH[2]}"
    
    - name: "Run SWAP steps"
      run: echo "------------- SWAP ${{ env.SLOT_1_NAME }} with ${{ env.SLOT_2_NAME }} !!"