name: ChatOps-DEPLOY

env:
  RESOURCE_GROUP: cd-demoactions
  LOCATION: westus2
  PLAN_NAME: cd-demoactionsplan
  SKU: S1
  WEB_APP_NAME: cd-demoactions
  SLOT_NAME: blue
  DOTNET_VERSION: 3.1.100

on:
  issue_comment:
    types: [ created, edited ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/deploy:')
    
    steps:
    #- uses: actions/checkout@v2

    - name: "Set env variables from chat message"
      run: |
        pattern="^\/deploy\:(\w+)$"
        [[ "${{ github.event.comment.body }}" =~ $pattern ]]
        echo ::set-env name=SLOT_NAME::"${BASH_REMATCH[1]}"
    
    - name: Create comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.comment.id }}
        body: |
          Deployment to ${{ env.SLOT_NAME }} is beginning!
        reaction-type: 'rocket'

    - name: "Run DEPLOY steps"
      run: echo "------------- DEPLOY to ${{ env.SLOT_NAME }}!!"
