name: ChatOps-ROUTE

env:
  RESOURCE_GROUP: cd-demoactions
  LOCATION: westus2
  PLAN_NAME: cd-demoactionsplan
  SKU: S1
  WEB_APP_NAME: cd-demoactions
  SLOT_NAME: blue
  DOTNET_VERSION: 3.1.100

on:
  issue_comment:
    types: [ created, edited ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/route:')
    
    steps:
    #- uses: actions/checkout@v2

    - name: "Set env variables from chat message"
      run: |
        pattern="^\/route\:(\w+)\,(.+)"
        [[ "${{ github.event.comment.body }}" =~ $pattern ]]
        echo ::set-env name=SLOT_NAME::"${BASH_REMATCH[1]}"
        echo ::set-env name=PERCENTAGE::"${BASH_REMATCH[2]}"
    
    - name: "Run ROUTE steps"
      run: echo "------------- ROUTE to ${{ env.SLOT_NAME }} with ${{ env.PERCENTAGE }} !!"