name: ChatOps-SWAP

env:
  RESOURCE_GROUP: cd-demoactions
  LOCATION: westus2
  PLAN_NAME: cd-demoactionsplan
  SKU: S1
  WEB_APP_NAME: cd-demoactions
  SLOT_NAME: blue
  DOTNET_VERSION: 3.1.100

on:
  issue_comment:
    types: [ created, edited ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/swap:')
    
    steps:
    - name: "Set env variables from chat message"
      run: |
        pattern="^\/swap\:(\w+)\,(\w+)$"
        [[ "${{ github.event.comment.body }}" =~ $pattern ]]
        echo ::set-env name=SLOT_1_NAME::"${BASH_REMATCH[1]}"
        echo ::set-env name=SLOT_2_NAME::"${BASH_REMATCH[2]}"
    
    - name: Create starting comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.issue.number }}
        body: |
          Hey, @${{ github.event.comment.user.login }}!
          :rocket: Operation to swap ${{ env.SLOT_1_NAME }} with ${{ env.SLOT_2_NAME }} is beginning! :rocket:
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Swap slots
      run: |
        az webapp deployment slot swap -g '${{ env.RESOURCE_GROUP }}' -n '${{ env.WEB_APP_NAME }}' --slot '${{ env.SLOT_1_NAME }}' --target-slot '${{ env.SLOT_2_NAME }}'

    - name: Create completed comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.issue.number }}
        body: |
          Hey, @${{ github.event.comment.user.login }}!
          :tada: Operation to swap ${{ env.SLOT_1_NAME }} with ${{ env.SLOT_2_NAME }} completed! :tada: