name: ChatOps-ROUTE

env:
  RESOURCE_GROUP: cd-demoactions
  LOCATION: westus2
  PLAN_NAME: cd-demoactionsplan
  SKU: S1
  WEB_APP_NAME: cd-demoactions
  SLOT_NAME: blue
  DOTNET_VERSION: 3.1.100

on:
  issue_comment:
    types: [ created, edited ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/route:')
    
    steps:
    - name: "Set env variables from chat message"
      run: |
        pattern="^\/route\:(\w+)\,(.+)"
        [[ "${{ github.event.comment.body }}" =~ $pattern ]]
        echo ::set-env name=SLOT_NAME::"${BASH_REMATCH[1]}"
        echo ::set-env name=PERCENTAGE::"${BASH_REMATCH[2]}"
    
    - name: Create starting comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.issue.number }}
        body: |
          Hey, @${{ github.event.comment.user.login }}!
          :rocket: Operation to route ${{ env.PERCENTAGE }} to ${{ env.SLOT_NAME }} is beginning! :rocket:

    - name: Route traffic to slot
      uses: colindembovsky/azure-webapp-route-traffic@v1.0.1
      with: 
        resource-group: ${{ env.RESOURCE_GROUP }}
        app-name: ${{ env.WEB_APP_NAME }}
        slot-name: ${{ env.SLOT_NAME }}
        percentage-traffic: ${{ env.PERCENTAGE }}

    - name: Create completed comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.issue.number }}
        body: |
          Hey, @${{ github.event.comment.user.login }}!
          :tada: Operation to route ${{ env.PERCENTAGE }} to ${{ env.SLOT_NAME }} completed! :tada:
